name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Install @changesets/cli
        run: yarn add @changesets/cli@2.27.1

      - name: Add changesets
        run: yarn changeset add

      - name: Commit changesets
        run: git add . && git commit -m "Add changesets" || echo "No changesets to commit"

      - name: Push changesets
        run: git push origin HEAD:${{ github.ref }}

      - name: Release packages
        run: yarn release
        uses: actions/checkout@v2

      - name: Setup Node.js 16.17.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Install Dependencies
        run: yarn

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.PROMOTE_GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
